### ISSUE TITLE
Deprecation warning for loggers section

### ISSUE THREAD

**Issue by hylkealons** [spandex-project/spandex_ecto#8]
```
warning: the :loggers configuration for Project.Repo is deprecated.

  * To customize the log level, set log: :debug | :info | :warn | :error instead
  * To disable logging, set log: false instead
  * To hook into logging events, see the "Telemetry Events" section in Ecto.Repo docs

  lib/ecto/repo/supervisor.ex:76: Ecto.Repo.Supervisor.compile_config/2
  lib/project/repo.ex:2: (module)
  (elixir) src/elixir_compiler.erl:71: :elixir_compiler.dispatch/4
  (elixir) src/elixir_compiler.erl:68: :elixir_compiler.compile/3
  (elixir) src/elixir_module.erl:286: :elixir_module.eval_form/6
  (elixir) src/elixir_module.erl:79: :elixir_module.compile/5
  (stdlib) erl_eval.erl:680: :erl_eval.do_apply/6
  (elixir) src/elixir.erl:265: :elixir.eval_forms/4
  (elixir) src/elixir_compiler.erl:49: :elixir_compiler.eval_forms/3
  (elixir) src/elixir_lexical.erl:17: :elixir_lexical.run/2
  (elixir) src/elixir_compiler.erl:23: :elixir_compiler.quoted/2
  (elixir) lib/kernel/parallel_compiler.ex:206: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/6
```

Is there a way to use the supported version?
https://hexdocs.pm/ecto/Ecto.Repo.html#module-telemetry-events

Ecto Version: 3.0.4

**Comment by duff** [comment]
I too am thinking about this one. I switched to start using the latest Ecto and Phoenix.

When I attempt to keep using the line from the README:

```
config :my_app, MyApp.Repo,
  loggers: [{Ecto.LogEntry, :log, [:info]}, {SpandexEcto.EctoLogger, :trace, ["database_name"]}]
```

I see errors running my tests:

```
    (elixir) lib/map.ex:437: Map.get(:ok, :queue_time, nil)
    (spandex_ecto) lib/spandex_ecto/ecto_logger.ex:104: SpandexEcto.EctoLogger.get_time/2
    (spandex_ecto) lib/spandex_ecto/ecto_logger.ex:28: SpandexEcto.EctoLogger.trace/2
    (elixir) lib/enum.ex:1925: Enum."-reduce/3-lists^foldl/2-0-"/3
    (db_connection) lib/db_connection.ex:1311: DBConnection.log/5
    (ecto_sql) lib/ecto/adapters/postgres/connection.ex:80: Ecto.Adapters.Postgres.Connection.execute/4
    (ecto_sql) lib/ecto/adapters/sql.ex:555: Ecto.Adapters.SQL.execute!/4
    (ecto_sql) lib/ecto/adapters/sql.ex:537: Ecto.Adapters.SQL.execute/5
    (ecto) lib/ecto/repo/queryable.ex:147: Ecto.Repo.Queryable.execute/4
    (ecto) lib/ecto/repo/queryable.ex:18: Ecto.Repo.Queryable.all/3
    (ecto) lib/ecto/repo/queryable.ex:66: Ecto.Repo.Queryable.one/3
```

Maybe the new ecto telemetry stuff can help?

**Comment by novaugust** [comment]
Just an FYI, it's possible to convert new telemetry events into maps resembling the old log entries and continue using `SpandexEcto.EctoLogger` sans warnings, **but**

- `num_rows` will always be 0
- `error` results will no longer be informative

```ex
defmodule MyApp.Tracer do
  # Add a trace_query function
  def trace_query([:my_app, :repo, :query], measurements, metadata, _config) do
    log_entry = %{
      query: metadata.query,
      source: metadata.source,
      params: metadata.params,
      query_time: measurements.query_time,
      decode_time: measurements.decode_time,
      queue_time: measurements.queue_time,
      result: {metadata.result, "n/a"} # "n/a" will be the name of the error if it's an error
    }

    SpandexEcto.EctoLogger.trace(log_entry, "my_database")
  end
end

# And then in application, per ecto docs
:telemetry.attach("spandex-query-tracer", [:my_app, :repo, :query], &MyApp.Tracer.trace_query/4)
```

**Comment by wiserfirst** [comment]
After merging #3070, I think this issue can be closed

**Comment by hylkealons** [comment]
thanks @wiserfirst. I am gonna test it out and reopen if the issue still exists 💪 .
